### ISSUE TITLE
errore su avvio it-fse-container-lite

### ISSUE THREAD

**Issue by ponsilva** [ministero-salute/it-fse-gtw-test-container#2]
Buongiorno,
sto provando ad avviare i container del gateway lite ma quando eseguo il comando
docker-compose up

ricevo un errore
[+] Building 0.1s (1/2)
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 2B                                                                                                                                     0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2660723126/Dockerfile: no such file or directory

Potete darmi indicazioni su come procedere per risolvere il problema?
Grazie

**Comment by zukka77** [comment]
Buongiorno sembra che docker non riesca a trovare un Dockerfile immagino per fare build del `it-fse-ms-runner` (container che scarica compila ed esegue i microservizi).
Controllerei di:

- aver fatto clonato tutto il repository (`git clone https://github.com/ministero-salute/it-fse-gtw-test-container.git `)
- di aver creato il file `.env` a partire dal file `.env-sample` all'interno della directory `it-fse-container-lite`
- di lanciare `docker-compose up`  dall'interno della directory `it-fse-container-lite`
- verificare eventualmente che altri docker-compose.yaml funzionino

**Comment by ponsilva** [comment]
Sì grazie, non avevo clonato tutto il repository

Adesso l'avvio procede ulteriormente e poi si verifica questo errore
[+] Building 1.8s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                        0.0s
 => ERROR [internal] load metadata for docker.io/library/maven:3-eclipse-temurin-17-focal                                                                              1.7s

 > [internal] load metadata for docker.io/library/maven:3-eclipse-temurin-17-focal:

failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fmaven%3Apull&service=registry.docker.io": read tcp 10.118.11.66:62945->34.205.13.154:443: wsarecv: Connessione in corso interrotta forzatamente dall'host remoto.

**Comment by zukka77** [comment]
Questo errore è dato durante il tentativo di scaricamento dell'immagine base su cui è costruito il container `it-fse-ms-runner`, la macchina ha accesso a internet e non ci sono configurazioni "strane" verso il registry di docker.io ?
Il semplice comando `docker pull docker.io/library/maven:3-eclipse-temurin-17-focal` va a buon fine ?

```
docker pull docker.io/library/maven:3-eclipse-temurin-17-focal
3-eclipse-temurin-17-focal: Pulling from library/maven
846c0b181fff: Already exists 
08b0873b98ac: Already exists 
44e7d9ad1d92: Already exists 
ab433a0a0933: Already exists 
0ff8cd76162c: Already exists 
02abf66a934d: Pull complete 
ada9dbaa68e8: Pull complete 
9d21f05540ca: Pull complete 
Digest: sha256:737f2013aa868a213347277f533ac9ec22b9f60213d50fd913c1c85e6adc0763
Status: Downloaded newer image for maven:3-eclipse-temurin-17-focal
docker.io/library/maven:3-eclipse-temurin-17-focal
```

**Comment by ponsilva** [comment]
Grazie dell'indicazione, evidentemente c'è una policy nella rete aziendale che blocca questa operazione.
Usano un accesso diretto a internet (senza proxy, senza vpn) riesco a concludere lo scaricamento delle immagini e l'avvio dei container.
Grazie per il supporto
